-- Supabase schema loader for ElevatED.
-- Use the sequential migrations under ./migrations to manage schema changes.
-- Example:
--   supabase migration up
--
-- To apply all migrations manually via psql:
--   \i ./migrations/001_core_schema.sql
--   \i ./migrations/002_seed_content.sql
