-- 042_success_metrics_analytics.sql
-- Lightweight analytics event sink + rollups for Success Metrics (Phase 8).

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  actor_role text not null check (actor_role in ('student', 'parent', 'admin', 'system')),
  student_id uuid references public.student_profiles(id) on delete set null,
  parent_id uuid references public.parent_profiles(id) on delete set null,
  occurred_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_name_time_idx
  on public.analytics_events (event_name, occurred_at desc);
create index if not exists analytics_events_student_time_idx
  on public.analytics_events (student_id, occurred_at desc);
create index if not exists analytics_events_parent_time_idx
  on public.analytics_events (parent_id, occurred_at desc);

alter table public.analytics_events enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'analytics_events'
      and policyname = 'analytics_events_admin_read'
  ) then
    execute 'create policy "analytics_events_admin_read" on public.analytics_events for select using (public.is_platform_admin())';
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'analytics_events'
      and policyname = 'analytics_events_service_manage'
  ) then
    execute 'create policy "analytics_events_service_manage" on public.analytics_events for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'')';
  end if;
end
$$;

grant select on public.analytics_events to authenticated;

-- Rollup view for Admin Success Metrics over the last 7 days.
create or replace view public.admin_success_metrics_rollup as
with lookback as (
  select now() - interval '7 days' as since, 7::int as lookback_days
),
weekly_accuracy as (
  select avg(nullif(payload->>'delta', '')::numeric) as weekly_accuracy_delta_avg
  from public.analytics_events, lookback
  where event_name = 'success_weekly_accuracy_delta'
    and occurred_at >= lookback.since
),
daily_plan as (
  select avg(student_day_max.pct)::numeric as daily_plan_completion_rate_avg
  from (
    select student_id,
           (payload->>'date')::date as activity_date,
           max(nullif(payload->>'pct', '')::numeric) as pct
    from public.analytics_events, lookback
    where event_name = 'success_daily_plan_progress'
      and occurred_at >= lookback.since
      and student_id is not null
      and payload ? 'pct'
      and payload ? 'date'
    group by student_id, (payload->>'date')::date
  ) student_day_max
),
alert_response as (
  select avg(nullif(payload->>'resolutionHours', '')::numeric) as alert_resolution_hours_avg
  from public.analytics_events, lookback
  where event_name = 'success_alert_resolved'
    and occurred_at >= lookback.since
    and payload ? 'resolutionHours'
)
select lookback.lookback_days,
       weekly_accuracy.weekly_accuracy_delta_avg,
       daily_plan.daily_plan_completion_rate_avg,
       alert_response.alert_resolution_hours_avg
from lookback
cross join weekly_accuracy
cross join daily_plan
cross join alert_response;

grant select on public.admin_success_metrics_rollup to authenticated;
